name: weather
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Corrected from ^5.0.0 to the latest valid version

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg  # Add this line for the background image